theme: jekyll-theme-cayman
title: How I discovered a free, unlimited premium currency bug at ArenaNet and all I got was $20
description: No, it's not missing a "k"
show_downloads: false
github:
  is_project_page: false
